name: komikoo
description: "Comic reader app with local tracking"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  auto_route: ^8.0.3
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  drift: ^2.16.0
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_widget_from_html_core: ^0.14.11
  fpdart: ^1.1.0
  grouped_list: ^5.1.2
  http: ^1.2.1
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.5
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  sqlite3: ^2.4.2
  sqlite3_flutter_libs: ^0.5.20
  timeago: ^3.6.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  drift_dev: ^2.16.0
  auto_route_generator: ^8.0.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/icon_background.png"
  adaptive_icon_foreground: "assets/images/icon_foreground.png"

flutter_native_splash:
  color: "#0DA6F4"
  image: assets/images/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
